### ISSUE TITLE
Error when applying configuration

### ISSUE THREAD

**Issue by Helly1206** [OpenMediaVault-Plugin-Developers/openmediavault-openvpn#29]
Hi,

When applying my openVPN configuration, I get the following error (sorry about the fonts and stuff, that's something github does):

Error #0:
OMV\ExecException: Failed to execute command 'export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin; export LANG=C.UTF-8; omv-salt deploy run openvpn 2>&1' with exit code '1': /usr/lib/python3/dist-packages/salt/utils/path.py:265: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  if not isinstance(exes, collections.Iterable):
raspberrypi.lan:
    Data failed to compile:
----------
    Rendering SLS 'base:omv.deploy.openvpn.default' failed: Jinja error: No 'type' attribute defined at 'clients.client'.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/salt/utils/templates.py", line 394, in render_jinja_tmpl
    output = template.render(**decoded_context)
  File "/usr/lib/python3/dist-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3/dist-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "<template>", line 18, in top-level template code
  File "/var/cache/salt/minion/extmods/modules/omv_conf.py", line 39, in get
    objs = db.get(id_, identifier)
  File "/usr/lib/python3/dist-packages/openmediavault/config/database.py", line 84, in get
    query = openmediavault.config.DatabaseGetQuery(id, identifier)
  File "/usr/lib/python3/dist-packages/openmediavault/config/database.py", line 685, in __init__
    super().__init__(id)
  File "/usr/lib/python3/dist-packages/openmediavault/config/database.py", line 312, in __init__
    self._parse_model()
  File "/usr/lib/python3/dist-packages/openmediavault/config/database.py", line 364, in _parse_model
    self.model.walk_schema("", callback, tags)
  File "/usr/lib/python3/dist-packages/openmediavault/config/datamodel.py", line 348, in walk_schema
    "", path, self.schema.get_by_path(path), callback, user_data
  File "/usr/lib/python3/dist-packages/openmediavault/config/datamodel.py", line 342, in _walk_schema
    prop_name, prop_path, prop_schema, callback, user_data
  File "/usr/lib/python3/dist-packages/openmediavault/config/datamodel.py", line 342, in _walk_schema
    prop_name, prop_path, prop_schema, callback, user_data
  File "/usr/lib/python3/dist-packages/openmediavault/config/datamodel.py", line 325, in _walk_schema
    _walk_schema(name, path, schema['items'], callback, user_data)
  File "/usr/lib/python3/dist-packages/openmediavault/config/datamodel.py", line 313, in _walk_schema
    "No 'type' attribute defined at '%s'." % path
openmediavault.json.schema.SchemaException: No 'type' attribute defined at 'clients.client'.

; line 18

---
[...]
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

{% set config = salt['omv_conf.get']('conf.service.openvpn') %}    <======================

{% if config.enable | to_bool %}

update_openmediavault_openvpn_config:
  cmd.run:
[...]
--- in /usr/share/php/openmediavault/system/process.inc:182
Stack trace:
#0 /usr/share/php/openmediavault/engine/module/serviceabstract.inc(60): OMV\System\Process->execute()
#1 /usr/share/openmediavault/engined/rpc/config.inc(167): OMV\Engine\Module\ServiceAbstract->deploy()
#2 [internal function]: Engined\Rpc\Config->applyChanges(Array, Array)
#3 /usr/share/php/openmediavault/rpc/serviceabstract.inc(123): call_user_func_array(Array, Array)
#4 /usr/share/php/openmediavault/rpc/serviceabstract.inc(149): OMV\Rpc\ServiceAbstract->callMethod('applyChanges', Array, Array)
#5 /usr/share/php/openmediavault/rpc/serviceabstract.inc(588): OMV\Rpc\ServiceAbstract->OMV\Rpc\{closure}('/tmp/bgstatusBU...', '/tmp/bgoutput0o...')
#6 /usr/share/php/openmediavault/rpc/serviceabstract.inc(159): OMV\Rpc\ServiceAbstract->execBgProc(Object(Closure))
#7 /usr/share/openmediavault/engined/rpc/config.inc(189): OMV\Rpc\ServiceAbstract->callMethodBg('applyChanges', Array, Array)
#8 [internal function]: Engined\Rpc\Config->applyChangesBg(Array, Array)
#9 /usr/share/php/openmediavault/rpc/serviceabstract.inc(123): call_user_func_array(Array, Array)
#10 /usr/share/php/openmediavault/rpc/rpc.inc(86): OMV\Rpc\ServiceAbstract->callMethod('applyChangesBg', Array, Array)
#11 /usr/sbin/omv-engined(537): OMV\Rpc\Rpc::call('Config', 'applyChangesBg', Array, Array, 1)
#12 {main}

I'm using OMV version 5.1.3-1.

Can anyone help solving this issue?

Thanks.

**Comment by Helly1206** [comment]
As the pull request with the solution is merged, I close this issue.
